name: Run bot

on:
#  schedule:
#  - cron: 58 12 25 09 *
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install engine
        run: |
          sudo apt update
          sudo apt install git build-essential meson ninja-build libopenblas-dev python3-pip
          pip3 install meson
          git clone -b https://github.com/LeelaChessZero/lc0.git
          cd lc0
          meson build --buildtype=release -Dbackend=openblas
          ninja -C build
          wget https://storage.lczero.org/files/networks-contrib/big-transformers/BT4-1740.pb.gz
          cd ..
          mv -f lc0/BT4-1740.pb.gz engines/BT4-1740.pb.gz
          mv -f lc0/build/release/lc0 engines/lc0
          rm -r lc0

      - name: Give perms to execute engine
        run: chmod +x ./engines/lc0

      - name: Replace token
        run: |
          sed -i 's|BOT_TOKEN|${{ secrets.BOT_TOKEN }}|g' config.yml

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }} 
        run: python user_interface.py --upgrade
